### ISSUE TITLE
Creating same issue for review

### ISSUE THREAD

**Issue by Dharmendhira** [Dharmendhira-SP/rahulshettypages_Ecommerce#4]
Please review the issue and close it. @Dharmendhira @Dharmendhira-SP 

- [ ] This one

[ ] This is two

`public void display()
{
System.out.println("Hell0");}`

**Comment by Dharmendhira-SP** [comment]
@Dharmendhira  we are looking into the issue now

**Comment by Dharmendhira-SP** [comment]
it has been closed now
